'use strict';
// V2: actual GPT-2 topology, symbolic data flow. Numerical v1 is an explicit separate mode.
const arch={mode:'architecture',group:0,head:0,block:0,hidden:0};
const originalRender=render,originalVisual=renderVisual;
const config=()=>families[state.family];
function archStats(c){return {width:c.d,heads:c.h,layers:c.l,headWidth:c.d/c.h,ff:4*c.d,groups:c.d/64,hiddenGroups:4*c.d/64,perBlock:12*c.d*c.d+10*c.d,total:2*50257*c.d+1024*c.d+c.l*(12*c.d*c.d+10*c.d)+2*c.d};}
function clickable(body,attr,id,label){return `<g class="clickable" ${attr}="${id}" role="button" tabindex="0" aria-label="${esc(label)}">${body}</g>`;}
function archRows(items){rows(items);}
function panel(title,desc,take){$('detail-title').textContent=title;$('explanation').innerHTML='<p>'+desc+'</p>';$('takeaway').textContent=take;}
function tiles(count,cols,x,y,w,h,label,selected,attr){let s='';for(let i=0;i<count;i++){const xx=x+i%cols*(w+9),yy=y+Math.floor(i/cols)*(h+10);s+=clickable(rect(xx,yy,w,h,label(i),'',i===selected),attr,i,label(i));}return s;}
function dimensionScene(){const c=config(),g=c.d/64,chosen=arch.group;
 controls('<span>Cada grupo contém 64 dimensões. Clique para abrir um grupo.</span>');
 let s=text(25,24,`VETOR DO TOKEN ${state.token} · ${nf(c.d)} DIMENSÕES`,'accent');
 s+=tiles(g,5,25,45,114,32,i=>`${i*64}–${i*64+63}`,chosen,'data-group');
 const y=65+Math.ceil(g/5)*42;s+=path(`M330 ${y-20} V${y+15}`,true)+text(330,y+36,`GRUPO ${chosen+1} · 64 DIMENSÕES INDIVIDUAIS`,'accent','middle');
 for(let i=0;i<64;i++){const x=72+(i%16)*34,yy=y+62+Math.floor(i/16)*36;s+=`<g><title>Dimensão ${chosen*64+i}; valor não calculado neste modo</title><circle cx="${x}" cy="${yy}" r="6" class="node"/></g>`;if(i%16===0)s+=text(20,yy+4,chosen*64+i);}
 $('visual').innerHTML=svg(s,y+210);
 archRows([['Dimensões desenhadas em grupos',`${g} × 64 = ${nf(c.d)}`],['Grupo aberto',`${chosen*64}–${chosen*64+63}`],['Token embeddings',`50.257 × ${nf(c.d)}`],['Posicionais',`1.024 × ${nf(c.d)}`]]);
 panel(state.step===1?'Uma linha com '+nf(c.d)+' pesos':'Somar duas linhas de '+nf(c.d)+' dimensões',state.step===1?'O ID seleciona uma linha da tabela de embeddings. Cada círculo aberto representa uma dimensão individual; os grupos acima cobrem o vetor completo.':'O embedding do token e o da posição têm a mesma largura. A soma é elemento a elemento; não duplica a dimensão. Na inferência, o dropout é identidade.','Ao trocar de família, a quantidade de grupos cresce de 12 até 25. Cada grupo sempre representa 64 dimensões.');
}
function normalizationArchitecture(){const c=config();let s=text(330,25,`${nf(c.d)} COMPONENTES DO MESMO TOKEN`,'accent','middle');s+=rect(30,88,170,70,'Vetor de entrada',`${c.d} dimensões`)+path('M200 123 H245',true)+rect(245,88,170,70,'LayerNorm','média / variância',true)+path('M415 123 H465',true)+rect(465,88,170,70,'Vetor normalizado',`${c.d} dimensões`);s+=text(330,214,'γ e β: um parâmetro por dimensão','','middle');s+=tiles(c.h,5,35,245,110,25,i=>`64 dims · ${i+1}`,arch.group,'data-group');$('visual').innerHTML=svg(s,270+Math.ceil(c.h/5)*35);archRows([['Eixo normalizado',`${c.d} dimensões`],['Escala γ',nf(c.d)],['Deslocamento β',nf(c.d)],['Parâmetros',nf(2*c.d)]]);}
function attentionArchitecture(){const c=config(),t=state.token,n=state.ids.length;
 controls(`<button id="arch-mask" aria-pressed="${state.causal}">${state.causal?'● Máscara causal ativa':'○ Sem máscara · comparação'}</button><span>Selecione qualquer uma das ${c.h} cabeças.</span>`);
 let s=text(330,23,`${c.d} DIMENSÕES → ${c.h} CABEÇAS × 64`,'accent','middle');s+=tiles(c.h,5,25,43,114,32,i=>'Cabeça '+(i+1),arch.head,'data-arch-head');let y=65+Math.ceil(c.h/5)*42;
 s+=path(`M330 ${y-20} V${y+10}`,true)+rect(120,y+15,420,58,`Cabeça ${arch.head+1}: dimensões ${arch.head*64}–${arch.head*64+63}`,'Q, K e V · cada um com 64 componentes',true);
 $('visual').innerHTML=svg(s,y+95)+`<div class="tagline">CONEXÕES PERMITIDAS · Q ↓ / K → · não são pesos numéricos</div><div class="matrix-wrap"><table class="matrix"><thead><tr><th>token</th>${state.ids.map((_,j)=>`<th>${j}</th>`).join('')}</tr></thead><tbody>${state.ids.map((id,i)=>`<tr><th>${i} ${esc(vocab[id])}</th>${state.ids.map((_,j)=>`<td><button data-arch-cell="${i},${j}" class="${state.causal&&j>i?'masked':''} ${i===t?'current':''}" aria-label="Query ${i}, key ${j}, ${state.causal&&j>i?'bloqueada':'permitida'}">${state.causal&&j>i?'—':'●'}</button></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 let connections='';for(let j=0;j<n;j++){const x=40+j*580/(n-1);if(!state.causal||j<=t)connections+=path(`M${x} 35 Q${x} 75 330 110`,true);connections+=neuron(x,30,1,j===t)+text(x,15,'V'+j,'','middle');}connections+=rect(200,110,260,45,'contexto: 64 dimensões','')+text(330,189,`Concatenar ${c.h} cabeças → ${c.d} → projeção Wₒ`,'accent','middle');$('visual').innerHTML+=svg(connections,215);
 archRows([['Cabeças distintas',c.h],['Dimensões / cabeça','64'],['Q / K / V',`cada matriz: ${c.d} × ${c.d}`],['Scores por cabeça',`${n} × ${n}`],['Divisor dos scores','√64 = 8'],['Concatenação',`${c.h} × 64 = ${c.d}`]]);
 panel('Cabeças reais da configuração',`Todas as ${c.h} cabeças estão representadas e podem ser selecionadas. Cada uma tem projeções próprias e opera sobre 64 componentes. A matriz mostra somente a estrutura causal.`, 'Mudar a cabeça altera o grupo de dimensões inspecionado. Sem pesos carregados, não inventamos diferenças numéricas de atenção.');
}
function residualArchitecture(){const c=config(),ff=state.step===7;let s=text(330,25,'DOIS CAMINHOS, A MESMA LARGURA','accent','middle');s+=rect(15,100,110,60,'x',`${c.d} dims`)+path('M125 130 H210',true)+rect(210,100,235,60,ff?'LayerNorm → FFN':'LayerNorm → atenção','atualização',true)+path('M445 130 H545',true)+path('M150 130 V60 H565 V110',true)+text(350,50,'atalho: cópia da entrada','','middle')+`<circle cx="565" cy="130" r="20" class="node-hot"/>`+text(565,135,'+','','middle')+path('M565 150 V230',true)+rect(385,235,255,60,'x + atualização',`${c.d} dimensões`,true);s+=text(50,255,`1 soma × ${nf(c.d)} componentes`,'accent')+text(50,279,'sem concatenar os vetores');$('visual').innerHTML=svg(s,345);archRows([['Entrada',`(1, ${state.ids.length}, ${c.d})`],['Atualização',`(1, ${state.ids.length}, ${c.d})`],['Saída',`(1, ${state.ids.length}, ${c.d})`],['Parâmetros da soma','0']]);}
function feedforwardArchitecture(){const c=config(),g=c.d/64,hg=4*g;
 controls(`<label>Grupo oculto <select id="arch-hidden">${Array.from({length:hg},(_,i)=>`<option value="${i}" ${i===arch.hidden?'selected':''}>${i*64}–${i*64+63}</option>`).join('')}</select></label><span>Cada nó = 64 neurônios. As linhas representam conexões entre grupos.</span>`);
 let s=text(55,24,`${c.d}`,'accent')+text(300,24,`${4*c.d} → GELU`,'accent','middle')+text(560,24,`${c.d}`,'accent');
 const hiddenPos=i=>[260+(i%4)*33,60+Math.floor(i/4)*15],hp=hiddenPos(arch.hidden);
 for(let i=0;i<g;i++){const y=60+i*15;s+=path(`M65 ${y} L${hp[0]} ${hp[1]}`,true)+path(`M${hp[0]} ${hp[1]} L580 ${y}`,true);s+=neuron(65,y,1)+neuron(580,y,1);}
 for(let i=0;i<hg;i++){const [x,y]=hiddenPos(i);s+=clickable(neuron(x,y,1,i===arch.hidden),'data-hidden',i,`Grupo oculto ${i+1}: neurônios ${i*64} a ${i*64+63}`);}
 const bottom=85+g*15;s+=text(65,bottom,`${g} grupos`,'','middle')+text(310,bottom,`${hg} grupos`,'','middle')+text(580,bottom,`${g} grupos`,'','middle')+text(330,bottom+36,'Uma linha entre dois grupos = 64 × 64 = 4.096 pesos','','middle');
 $('visual').innerHTML=svg(s,bottom+70);archRows([['Entrada → expansão → saída',`${c.d} → ${4*c.d} → ${c.d}`],['Neurônios ocultos',nf(4*c.d)],['Grupo selecionado',`${arch.hidden*64}–${arch.hidden*64+63}`],['Pesos + biases FFN',nf(8*c.d*c.d+5*c.d)]]);
 panel('A rede densa também cresce',`No GPT-2 ${c.name}, cada token passa por ${nf(4*c.d)} neurônios ocultos. As conexões destacadas mostram todos os grupos de entrada e saída conectados ao grupo selecionado.`,`São ${nf(8*c.d*c.d)} pesos nas duas projeções. Agrupamos neurônios para mostrar a rede inteira sem desenhar milhões de linhas.`);
}
function blocksArchitecture(){const c=config(),cols=6,rowsN=Math.ceil(c.l/cols);controls('<span>Cada bloco é uma instância distinta. Clique para inspecionar qualquer bloco.</span>');let s=text(330,23,`${c.l} TRANSFORMER BLOCKS · ${c.d} DIMENSÕES EM CADA ETAPA`,'accent','middle');
 for(let i=0;i<c.l;i++){let x=22+(i%cols)*106,y=49+Math.floor(i/cols)*62;if(i<c.l-1){if(i%cols<cols-1)s+=path(`M${x+86} ${y+20} H${x+106}`,true);else s+=path(`M${x+86} ${y+20} H650 V${y+49} H12 V${y+82} H22`,true);}s+=clickable(rect(x,y,86,40,'Bloco '+(i+1),'',i===arch.block),'data-arch-block',i,'Inspecionar bloco '+(i+1));}
 const y=62+rowsN*62;s+=rect(30,y,600,72,`Bloco ${arch.block+1} · parâmetros independentes`,'LN → atenção → residual → LN → FFN → residual',true);$('visual').innerHTML=svg(s,y+100);archRows([['Blocos desenhados',c.l],['Bloco selecionado',arch.block+1],['Parâmetros / bloco',nf(archStats(c).perBlock)],['Dimensão preservada',c.d]]);panel('Cada retângulo é um bloco real',`A família ${c.name} empilha ${c.l} blocos. Os conectores seguem a ordem numérica, da esquerda para a direita; ao fim de uma linha, o fluxo continua no início da próxima.`, 'O seletor muda a quantidade de blocos desenhados. A animação indica a direção do fluxo, não tempo de processamento ou ativações calculadas.');
}
function outputArchitecture(){const c=config();let s=rect(25,38,160,65,'Vetor final',`${c.d} dimensões`)+path('M185 70 H255',true)+rect(255,38,190,65,'Cabeça de saída',`${c.d} × 50.257`,true)+path('M445 70 H500',true)+rect(500,38,140,65,'Logits','50.257');s+=text(330,152,'VOCABULÁRIO COMPLETO · GRUPOS DE ATÉ 1.024 ENTRADAS','','middle');for(let i=0;i<50;i++){let x=30+(i%10)*62,y=177+Math.floor(i/10)*33;s+=`<g><title>Logits ${i*1024}–${Math.min(50256,(i+1)*1024-1)}</title>`+rect(x,y,52,25,i===49?'81':'1.024','')+'</g>';}$('visual').innerHTML=svg(s,370);archRows([['Dimensões lidas',c.d],['Logits / token','50.257'],['Parâmetros da saída',nf(c.d*50257)],['Bias','Não']]);panel('A largura muda; o vocabulário permanece',`A projeção recebe ${c.d} dimensões no modelo ${c.name} e produz 50.257 logits por posição. Os 49 primeiros grupos têm 1.024 entradas; o último tem 81.`, 'Não há probabilidades neste modo estrutural. A distribuição numérica do mini-GPT pode ser explorada no Laboratório numérico.');}
function generationArchitecture(){const c=config(),chosen=nextGuided(state.ids);controls('<span>Continuação guiada · IDs locais · nenhuma inferência GPT-2 executada</span>');$('title').textContent='A frase volta para a arquitetura escolhida.';$('intro').textContent='Acrescente um token do roteiro e observe como o tamanho da sequência altera todos os shapes.';
 $('visual').innerHTML=`<div class="big-text">${esc(state.ids.map(id=>vocab[id]).join(''))}<span> ▍</span></div><div class="tagline">${state.ids.length} tokens · GPT-2 ${c.name} · ${c.l} blocos × ${c.h} cabeças</div><button id="arch-generate" class="primary" ${chosen===null?'disabled':''}>${chosen===null?'✓ Frase completa':'Adicionar “'+esc(vocab[chosen])+'” →'}</button>`+svg(path('M115 98 H255',true)+rect(15,65,180,65,'Contexto',`${state.ids.length} tokens`)+rect(255,65,180,65,`${c.l} blocos`,`${c.d} dimensões`,true)+path('M435 98 H485',true)+rect(485,65,160,65,'Saída','50.257 logits')+path('M565 130 V193 H100 V132',true)+text(330,219,'anexar token → novo contexto → repetir o percurso','','middle'),245);
 archRows([['Token do roteiro',chosen===null?'Concluído':esc(vocab[chosen])],['Sequência atual',state.ids.length],['Blocos por rodada',c.l],['Atividades de atenção',`${c.l} × ${c.h} cabeças`]]);panel('Roteiro guiado, arquitetura variável','A frase “Hello, I am a GPT built from scratch” é escolhida por nós. O esquema percorre a arquitetura selecionada, mas não calcula um forward pass de GPT-2. Os tokens usados aqui têm a segmentação local da demonstração.','Volte às etapas anteriores para inspecionar a matriz causal e os shapes com o contexto ampliado.');$('code').textContent='# Estrutura do laço; a frase deste modo é guiada\nfor token_id in continuation:\n    idx = torch.cat((idx, token_id), dim=1)\n    # Próxima rodada: todos os blocos recebem o novo contexto.';
}
function architectureVisual(){const c=config();controls('');$('visual').className='architecture-view';switch(state.step){case 0:tokenScene();panel('Mesmos tokens, arquitetura diferente','A escolha Small–XL não altera a tokenização. Nesta apresentação usamos IDs locais para a frase, e não um tokenizer GPT-2 completo.','A partir do embedding, a largura dos vetores passa a acompanhar o modelo escolhido.');break;case 1:case 2:dimensionScene();break;case 3:case 9:normalizationArchitecture();break;case 4:attentionArchitecture();break;case 5:case 7:residualArchitecture();break;case 6:feedforwardArchitecture();break;case 8:blocksArchitecture();break;case 10:outputArchitecture();break;case 11:generationArchitecture();break;}
 caption(`<b>Arquitetura GPT-2 ${c.name}: ${c.d} dimensões · ${c.h} cabeças · ${c.l} blocos.</b> Fluxo esquemático, sem pesos carregados ou execução numérica. Grupos têm sua escala indicada no diagrama.`);
}
renderVisual=function(){if(arch.mode==='architecture')architectureVisual();else originalVisual();};
render=function(){
 originalRender();const c=config(),stats=archStats(c),numeric=arch.mode==='numeric';
 document.body.classList.toggle('architecture-mode',!numeric);
 $('model-status').textContent=numeric?'Mini-GPT numérico':'GPT-2 '+c.name+' · arquitetura';
 $('model-description').textContent=numeric?'8 dimensões · 2 cabeças · 2 blocos. Pesos fixos, sem treino.':`${c.d} dimensões · ${c.h} cabeças · ${c.l} blocos. Fluxo esquemático, sem inferência.`;
 $('mode-note').textContent=numeric?'Cálculos do mini-GPT; seletor GPT-2 só como referência.':'O seletor muda a rede desenhada. Valores numéricos estão no laboratório separado.';
 if(!numeric){const t=state.ids.length,shape=`(1, ${t}, ${c.d})`;$('shape-in').textContent=state.step===0?'Texto':state.step===1||state.step===11?`(1, ${t})`:shape;$('shape-out').textContent=state.step===0?`(1, ${t})`:state.step===10?`(1, ${t}, 50.257)`:state.step===11?(nextGuided(state.ids)===null?'Frase completa':`(1, ${t+1})`):shape;$('real-label').textContent='ARQUITETURA SELECIONADA';$('real-shape').textContent=`D ${c.d} · H ${c.h} · L ${c.l}`;$('reference').innerHTML=`<b>GPT-2 ${c.name}</b> · ${nf(stats.total)} parâmetros<br>${nf(stats.perBlock)} por bloco · FFN ${c.d} → ${4*c.d} → ${c.d}<br>Vocab. 50.257 · contexto máx. 1.024 · QKV sem bias.<br>Esta vista não aloca ou executa esses pesos.`;}
 document.querySelectorAll('.tensor-strip>div>span').forEach((el,i)=>{if(i<2)el.textContent=(numeric?'MINI-GPT':'GPT-2 '+c.name.toUpperCase())+' · '+(i===0?'ENTRADA':'SAÍDA');});
};
$('family').onchange=e=>{pause();state.family=Number(e.target.value);arch.group=Math.min(arch.group,config().d/64-1);arch.head=Math.min(arch.head,config().h-1);arch.block=Math.min(arch.block,config().l-1);arch.hidden=Math.min(arch.hidden,config().d/16-1);render();};
$('exploration').onchange=e=>{pause();arch.mode=e.target.value;if(arch.mode==='architecture'&&nextGuided(state.ids)===null&&state.ids.join()!==guidedIds.join()){state.ids=[0,1,2,3];state.token=3;}state.generation='guided';data=forward(state.ids,state.causal);render();};
document.addEventListener('click',e=>{if(arch.mode!=='architecture')return;const b=e.target.closest('[data-group],[data-arch-head],[data-arch-block],[data-hidden],[data-arch-cell],#arch-mask,#arch-generate');if(!b)return;if(b.dataset.group!==undefined)arch.group=Number(b.dataset.group);if(b.dataset.archHead!==undefined)arch.head=Number(b.dataset.archHead);if(b.dataset.archBlock!==undefined)arch.block=Number(b.dataset.archBlock);if(b.dataset.hidden!==undefined)arch.hidden=Number(b.dataset.hidden);if(b.dataset.archCell!==undefined)state.token=Number(b.dataset.archCell.split(',')[0]);if(b.id==='arch-mask'){state.causal=!state.causal;data=forward(state.ids,state.causal);}if(b.id==='arch-generate'){const id=nextGuided(state.ids);if(id===null)return;state.ids.push(id);state.token=state.ids.length-1;data=forward(state.ids,state.causal);}render();});
document.addEventListener('change',e=>{if(e.target.id==='arch-hidden'){arch.hidden=Number(e.target.value);renderVisual();}});
render();
