'use strict';
// Interaction layer for the symbolic architecture: lookup, individual dimensions,
// operation walkthroughs and inspectors. No simulated GPT-2 activations.
const interaction={phase:0,dimension:0,output:0,outputOffset:0,key:0,flowTimer:null,contextKey:''};
const operationSteps=[
 [['Texto','A frase entra como uma sequência de caracteres.'],['Tokenizar','O tokenizer divide o texto em unidades do vocabulário. Aqui a frase usa a segmentação local da demonstração.'],['IDs','Cada unidade recebe um índice de vocabulário; um ID não é um valor semântico.']],
 [['Selecionar token','Clique em uma linha da tabela abaixo. O token seleciona um embedding, não uma multiplicação pelo número do ID.'],['Buscar linha','A busca lê somente a linha correspondente da tabela E, que tem 50.257 linhas. A tabela abaixo mostra um recorte dos tokens do contexto.'],['Abrir vetor','Escolha um grupo e clique em uma das 64 dimensões para rastrear sua origem: E[token, dimensão].']],
 [['Token','E[token, d] fornece a identidade do token na dimensão d.'],['Posição','P[posição, d] fornece a informação da posição na mesma dimensão.'],['Somar','x[posição, d] = E[token, d] + P[posição, d]. A soma preserva D dimensões.'],['Dropout','Na inferência, dropout é identidade. No treino, ativações são zeradas aleatoriamente e as restantes são reescaladas.']],
 [['Média','μ = soma(x[d]) / D. Todos os componentes do token selecionado participam da média.'],['Variância','σ² = soma((x[d] − μ)²) / D, com variância populacional.'],['Normalizar','z[d] = (x[d] − μ) / √(σ² + ε).'],['Escala + shift','y[d] = γ[d] × z[d] + β[d]. Clique numa dimensão para identificar seus parâmetros.']],
 [['Q, K, V','A entrada é projetada separadamente em queries, keys e values.'],['Q × Kᵀ','A query selecionada é comparada às keys de todas as posições. Cada cabeça usa 64 componentes.'],['Máscara','As posições futuras são bloqueadas antes do softmax. Clique numa célula para inspecionar a conexão.'],['Softmax','Os scores são divididos por √64 = 8; softmax normaliza os pesos da linha.'],['Combinar V','Cada value contribui de acordo com seu peso. As cabeças são concatenadas e projetadas de volta a D.']],
 [['Guardar x','O atalho conserva a entrada original, antes da primeira LayerNorm.'],['Atualizar','A entrada normalizada passa pela atenção e pelo dropout, desligado na inferência.'],['Somar','y[d] = x[d] + atualização[d]. Os dois caminhos têm exatamente D componentes.']],
 [['Normalizar','LayerNorm prepara o vetor da posição selecionada.'],['Expandir','W₁ combina D entradas para cada um dos 4D neurônios ocultos, com bias.'],['GELU','A não linearidade transforma cada pré-ativação. Explore a curva com o controle abaixo.'],['Comprimir','W₂ combina 4D ativações para produzir uma atualização com D componentes.']],
 [['Guardar x','Este atalho preserva a saída da primeira residual.'],['Atualizar','LayerNorm → feed-forward → dropout produz a nova atualização.'],['Somar','Saída do bloco = primeira residual + atualização do feed-forward.']],
 [['Entrada','O bloco selecionado recebe a saída do anterior (ou os embeddings, no bloco 1).'],['Atenção + residual','LayerNorm → multi-head attention → dropout → primeira soma residual.'],['FFN + residual','LayerNorm → expansão → GELU → compressão → dropout → segunda soma residual.'],['Próximo bloco','A saída mantém (B, T, D) e alimenta o próximo bloco, com parâmetros independentes.']],
 [['Média','Calculada nas D componentes da saída do último bloco, para um token.'],['Variância','A variância usa a mesma linha do tensor, sem misturar tokens.'],['Normalizar','Subtrair a média e dividir pelo desvio padrão estabilizado por ε.'],['Escala + shift','A LayerNorm final tem seus próprios γ e β, independentes dos blocos.']],
 [['Vetor final','A cabeça de saída recebe D componentes da posição selecionada.'],['Projeção','Cada logit combina todos os D componentes com uma coluna da matriz de saída.'],['Logits','Escolha um grupo e um índice de saída para rastrear sua coluna de pesos.'],['Softmax','Transforma os 50.257 logits em uma distribuição. Não calculamos essas probabilidades neste modo.']],
 [['Selecionar','O próximo token é definido pelo roteiro guiado.'],['Anexar','Um ID é acrescentado ao fim do contexto. Use o botão Adicionar para realizar essa ação.'],['Recomeçar','A próxima rodada recebe a sequência ampliada. A animação ilustra o percurso; não executa GPT-2.']]
];
function stopOperation(){if(interaction.flowTimer)clearInterval(interaction.flowTimer);interaction.flowTimer=null;}
function dimInspector(){const c=config(),d=arch.group*64+interaction.dimension;return [['Token / posição',esc(vocab[state.ids[state.token]])+' / '+state.token],['Dimensão individual',d],['Origem do embedding',`E[token, ${d}]`],['Posição',`P[${state.token}, ${d}]`],['Soma',`E[token, ${d}] + P[${state.token}, ${d}]`],['Valores','Não carregados neste modo']];}
function dimensionGrid(y,group=arch.group,attr='data-dimension'){let s='';for(let i=0;i<64;i++){const x=74+(i%16)*34,yy=y+Math.floor(i/16)*36;s+=clickable(neuron(x,yy,1,i===interaction.dimension),attr,i,`Inspecionar dimensão ${group*64+i}`);if(i%16===0)s+=text(15,yy+4,group*64+i);}return s;}
const basicDimensions=dimensionScene;
dimensionScene=function(){
 const c=config(),n=state.ids.length,g=c.d/64;
 if(state.step===2){controls('<span>Clique em um operando, grupo ou dimensão para acompanhar a soma.</span>');let s=text(330,22,`COMPONENTE ${arch.group*64+interaction.dimension} · TOKEN ${state.token}`,'accent','middle');
 ['E[token, d]','P[posição, d]','x[posição, d]'].forEach((label,i)=>{s+=clickable(rect(25+i*220,60,170,58,label,'',interaction.phase===i),'data-operation',i,label);if(i<2)s+=text(215+i*220,96,i===0?'+':'=','accent','middle');});s+=tiles(g,5,25,170,114,32,i=>`${i*64}–${i*64+63}`,arch.group,'data-group');const y=210+Math.ceil(g/5)*42;s+=text(330,y-20,'ABRA UMA DIMENSÃO DA SOMA','accent','middle')+dimensionGrid(y+15);$('visual').innerHTML=svg(s,y+160);archRows(dimInspector());panel('Identidade e posição, componente a componente','O componente selecionado recebe a soma de dois pesos: um da tabela de tokens e outro da tabela de posições. Os operandos e o resultado preservam a mesma largura.','O dropout é identidade na inferência; a soma não concatena os dois vetores.');return;}
 controls('<span>1. Clique no token na tabela → 2. Abra um grupo → 3. Inspecione uma dimensão.</span>');
 let s=text(330,24,`TABELA E · 50.257 × ${nf(c.d)} · RECORTE DO CONTEXTO`,'accent','middle');
 for(let i=0;i<n;i++){const y=52+i*38,hot=i===state.token;s+=clickable(rect(10,y-5,113,31,vocab[state.ids[i]],'',hot),'data-lookup',i,'Buscar embedding de '+vocab[state.ids[i]]+' na posição '+i);s+=path(`M123 ${y+10} H155`,hot);
 for(let j=0;j<g;j++){s+=clickable(`<rect x="${158+j*18}" y="${y}" width="14" height="22" rx="3" fill="${hot&&interaction.phase>0?'#c6f279':'#304033'}" opacity="${hot&&j!==arch.group?.55:1}" stroke="${hot&&j===arch.group?'#fff':'none'}"/>`,'data-lookup-group',i+','+j,`Token na posição ${i}, dimensões ${j*64} a ${j*64+63}`);}}
 let y=68+n*38;s+=text(330,y,'Cada célula da linha representa 64 dimensões.','','middle');s+=path(`M330 ${y+12} V${y+37}`,true);y+=65;s+=text(330,y,`LINHA SELECIONADA: “${vocab[state.ids[state.token]]}” → ${nf(c.d)} COMPONENTES`,'accent','middle');s+='<g opacity="'+(interaction.phase===2?1:.4)+'">'+tiles(g,5,25,y+22,114,32,i=>`${i*64}–${i*64+63}`,arch.group,'data-group')+'</g>';y+=Math.ceil(g/5)*42+80;s+=text(330,y-25,'CLIQUE EM UM DOS 64 COMPONENTES DO GRUPO','accent','middle')+dimensionGrid(y);$('visual').innerHTML=svg(s,y+145);$('visual').classList.add('lookup-phase-'+interaction.phase);archRows(dimInspector());panel('O lookup agora é explorável','Selecione a linha, acompanhe o caminho destacado e abra qualquer componente do embedding. A tabela é um recorte das ocorrências no contexto: tokens repetidos consultam a mesma linha de E.','Mudar a posição seleciona outra ocorrência; o token determina qual embedding é buscado. Nenhum valor de peso é inventado.');
};
const basicNormalization=normalizationArchitecture;
normalizationArchitecture=function(){basicNormalization();const c=config(),d=arch.group*64+interaction.dimension;$('visual').innerHTML+=svg(text(330,24,`GRUPO ${arch.group+1} · CLIQUE EM UMA DIMENSÃO`,'accent','middle')+dimensionGrid(55),185);archRows([['Token normalizado',state.token],['Dimensão selecionada',d],['Média / variância',`usam todas as ${c.d} dimensões`],['Parâmetros desta dimensão',`γ[${d}] e β[${d}]`],['Saída',`γ[${d}] × z[${d}] + β[${d}]`]]);};
const basicAttentionInteractive=attentionArchitecture;
attentionArchitecture=function(){basicAttentionInteractive();const k=Math.min(interaction.key,state.ids.length-1),q=state.token,blocked=state.causal&&k>q;archRows([['Cabeça inspecionada',arch.head+1],['Query → key',`${q} → ${k}`],['Conexão',blocked?'Bloqueada: futuro':'Permitida'],['Score',blocked?'−∞ após máscara':`Q[${q}] · K[${k}] / 8`],['Value consultado',blocked?'Não contribui':`V[${k}], 64 componentes`],['Peso','Não calculado neste modo']]);};
const basicResidual=residualArchitecture;
residualArchitecture=function(){basicResidual();const el=$('visual');el.innerHTML=el.innerHTML.replace('class="node-hot"','class="node-hot" data-operation="2" role="button" tabindex="0" aria-label="Inspecionar soma residual"');let extra='<div class="branch-buttons"><button data-operation="0">Seguir o atalho ↗</button><button data-operation="1">Seguir a atualização →</button><button data-operation="2">Encontrar na soma +</button></div>';el.insertAdjacentHTML('afterbegin',extra);el.querySelectorAll('path').forEach(p=>{const shortcut=p.getAttribute('d').startsWith('M150');const active=interaction.phase===2||(interaction.phase===0?shortcut:!shortcut);p.setAttribute('class',active?'flow':'wire');});archRows([['Caminho selecionado',operationSteps[state.step][interaction.phase][0]],['Dimensão inspecionada',arch.group*64+interaction.dimension],['Operação',`x[d] + atualização[d]`],['Largura preservada',config().d]]);};
const basicFF=feedforwardArchitecture;
function geluExplorer(){const x=state.geluX,px=z=>150+(z+3)*55,py=z=>140-z*32;let curve='';for(let v=-3;v<=3.001;v+=.05)curve+=(curve?'L':'M')+px(v)+' '+py(gelu(v));return svg(text(330,20,'EXPLORADOR GELU · NÃO ALTERA A REDE','accent','middle')+path('M150 140 H485')+path('M315 40 V165')+`<path d="${curve}" fill="none" stroke="#c6f279" stroke-width="2"/>`+neuron(px(x),py(gelu(x)),1,true)+text(330,198,`x = ${f(x,2)} → GELU(x) = ${f(gelu(x),4)}`,'accent','middle'),220);}
feedforwardArchitecture=function(){basicFF();$('stage-controls').insertAdjacentHTML('beforeend',`<label>Explorar GELU <input id="arch-gelu" type="range" min="-3" max="3" step=".05" value="${state.geluX}"></label>`);$('visual').innerHTML+=`<div id="arch-gelu-plot">${geluExplorer()}</div>`;};
const basicBlocks=blocksArchitecture;
blocksArchitecture=function(){basicBlocks();$('visual').insertAdjacentHTML('beforeend','<div class="branch-buttons"><button id="previous-block" '+(arch.block===0?'disabled':'')+'>← Bloco anterior</button><button id="next-block" '+(arch.block===config().l-1?'disabled':'')+'>Próximo bloco →</button></div>');};
outputArchitecture=function(){const c=config(),start=interaction.output*1024,end=Math.min(50256,start+1023);let s=rect(20,30,170,60,'Vetor do token',`${c.d} dimensões`)+path('M190 60 H265',true)+rect(265,30,235,60,`Coluna de W: logit ${start+interaction.outputOffset}`,`${c.d} pesos`,true)+path('M500 60 H545',true)+rect(545,30,95,60,'logit','sem bias');s+=text(330,130,'CLIQUE EM UM GRUPO DO VOCABULÁRIO','accent','middle');for(let i=0;i<50;i++){s+=clickable(rect(20+(i%10)*63,155+Math.floor(i/10)*36,55,28,i===49?'81':'1.024','',i===interaction.output),'data-output-group',i,`Logits ${i*1024} a ${Math.min(50256,i*1024+1023)}`);}s+=text(330,367,`GRUPO ${interaction.output+1}: LOGITS ${start}–${end}`,'accent','middle');$('visual').innerHTML=svg(s,400);controls(`<label>Logit no grupo <input id="arch-logit" type="number" min="${start}" max="${end}" value="${start+interaction.outputOffset}"></label><button id="inspect-logit">Inspecionar coluna →</button><span>Clique nos grupos e escolha uma coluna de pesos.</span>`);archRows([['Logit selecionado',start+interaction.outputOffset],['Coluna de pesos',`${c.d} componentes`],['Operação',`Σ x[d] × W[d, ${start+interaction.outputOffset}]`],['Bias','Não'],['Grupo',`${start}–${end}`],['Valor do logit','Não calculado neste modo']]);panel('Cada saída tem uma coluna de pesos','Escolher um logit destaca a projeção que o produz. Todos os componentes do vetor final contribuem para esse logit. A coluna pertence ao vocabulário GPT-2, mas seus pesos não estão carregados.','A inspeção rastreia a operação; não atribui um token ou uma probabilidade a um índice sem um tokenizer e pesos carregados.');};
function operationUI(){const phases=operationSteps[state.step],active=interaction.phase;let html='<div class="operation-walk"><div class="operation-top"><span>EXPLORE A OPERAÇÃO · '+(active+1)+'/'+phases.length+'</span><button id="animate-operation">'+(interaction.flowTimer?'Ⅱ Pausar operação':'▶ Animar operação')+'</button></div><div class="operation-phases">';html+=phases.map((p,i)=>`<button data-operation="${i}" class="${i===active?'active':''}" aria-pressed="${i===active}"><span>${i+1}</span>${p[0]}</button>`).join('');html+='</div><p class="operation-description" aria-live="polite">'+phases[active][1]+'</p><div class="operation-track"><span style="width:'+((active+1)/phases.length*100)+'%"></span></div></div>';$('visual').insertAdjacentHTML('afterbegin',html);$('visual').dataset.phase=active;}
const interactiveArchitecture=architectureVisual;
architectureVisual=function(){const context=[state.step,state.family,arch.mode].join(':');if(context!==interaction.contextKey){stopOperation();interaction.phase=0;interaction.contextKey=context;}interactiveArchitecture();operationUI();};
function refreshOperation(){renderVisual();}
document.addEventListener('click',e=>{if(arch.mode!=='architecture')return;const b=e.target.closest('[data-operation],[data-lookup],[data-lookup-group],[data-dimension],[data-output-group],#animate-operation,#previous-block,#next-block,#inspect-logit,[data-arch-cell]');if(!b)return;
 if(b.id==='animate-operation'){if(interaction.flowTimer){stopOperation();refreshOperation();return;}interaction.phase=0;interaction.flowTimer=setInterval(()=>{const last=operationSteps[state.step].length-1;if(interaction.phase<last)interaction.phase++;if(interaction.phase===last)stopOperation();refreshOperation();},1400);refreshOperation();return;}
 stopOperation();
 if(b.id==='inspect-logit'){const start=interaction.output*1024,end=Math.min(50256,start+1023),v=Number($('arch-logit').value);interaction.outputOffset=Number.isFinite(v)?Math.max(start,Math.min(end,Math.trunc(v)))-start:0;}
 if(b.dataset.archCell!==undefined){interaction.key=Number(b.dataset.archCell.split(',')[1]);interaction.phase=2;}
 if(b.dataset.operation!==undefined)interaction.phase=Number(b.dataset.operation);
 if(b.dataset.lookup!==undefined){state.token=Number(b.dataset.lookup);interaction.phase=1;}
 if(b.dataset.lookupGroup!==undefined){const [t,g]=b.dataset.lookupGroup.split(',').map(Number);state.token=t;arch.group=g;interaction.phase=2;}
 if(b.dataset.dimension!==undefined){interaction.dimension=Number(b.dataset.dimension);interaction.phase=Math.min(2,operationSteps[state.step].length-1);}
 if(b.dataset.outputGroup!==undefined){interaction.output=Number(b.dataset.outputGroup);interaction.outputOffset=0;interaction.phase=2;}
 if(b.id==='previous-block')arch.block=Math.max(0,arch.block-1);
 if(b.id==='next-block')arch.block=Math.min(config().l-1,arch.block+1);
 render();
});
document.addEventListener('input',e=>{if(arch.mode==='architecture'&&e.target.id==='arch-gelu'){state.geluX=Number(e.target.value);$('arch-gelu-plot').innerHTML=geluExplorer();}});
document.addEventListener('change',e=>{if(e.target.id==='arch-logit'){const start=interaction.output*1024,end=Math.min(50256,start+1023),v=Number(e.target.value);interaction.outputOffset=Number.isFinite(v)?Math.max(start,Math.min(end,Math.trunc(v)))-start:0;refreshOperation();}if(e.target.id==='exploration'){stopOperation();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopOperation();});
render();
