'use strict';
/* Mini-GPT didático: forward numérico, pesos fixos não treinados, sem dependências. */
const D=8,H=2,MAX_T=12;
const vocab=['Hello',',',' I',' am',' a',' model','.','?',' GPT',' built',' from',' scratch'];
const V=vocab.length;
const guidedIds=[0,1,2,3,4,8,9,10,11];
function nextGuided(ids){return ids.every((id,i)=>id===guidedIds[i]) ? (guidedIds[ids.length] ?? null) : null;}
const families=[{name:'Small',d:768,h:12,l:12},{name:'Medium',d:1024,h:16,l:24},{name:'Large',d:1280,h:20,l:36},{name:'XL',d:1600,h:25,l:48}];
let seed=123;
function random(){seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;}
const weights=(a,b,scale=.35)=>Array.from({length:a},()=>Array.from({length:b},()=>(random()*2-1)*scale));
const matmul=(a,b)=>a.map(row=>b[0].map((_,j)=>row.reduce((s,v,k)=>s+v*b[k][j],0)));
const add=(a,b)=>a.map((r,i)=>r.map((v,j)=>v+b[i][j]));
const normRow=r=>{const mean=r.reduce((s,x)=>s+x,0)/r.length;const variance=r.reduce((s,x)=>s+(x-mean)**2,0)/r.length;return r.map(x=>(x-mean)/Math.sqrt(variance+1e-5));};
const norm=a=>a.map(normRow);
const gelu=x=>.5*x*(1+Math.tanh(Math.sqrt(2/Math.PI)*(x+.044715*x*x*x)));
const softmax=r=>{const m=Math.max(...r),e=r.map(x=>Math.exp(x-m)),s=e.reduce((a,b)=>a+b,0);return e.map(x=>x/s);};
const tokW=weights(V,D,.8),posW=weights(MAX_T,D,.3);
const blocks=Array.from({length:2},()=>({q:weights(D,D),k:weights(D,D),v:weights(D,D),o:weights(D,D),ob:weights(1,D,.04)[0],up:weights(D,4*D),ub:weights(1,4*D,.04)[0],down:weights(4*D,D),db:weights(1,D,.04)[0]}));
const outW=weights(D,V,.6);
const linear=(x,w,b)=>matmul(x,w).map(r=>r.map((v,j)=>v+(b?b[j]:0)));
function blockForward(x,w,causal=true){
 const n1=norm(x),q=matmul(n1,w.q),k=matmul(n1,w.k),v=matmul(n1,w.v),scores=[],attention=[];
 for(let h=0;h<H;h++){
  scores[h]=q.map((r,i)=>k.map((kr,j)=>r.slice(h*4,h*4+4).reduce((s,z,c)=>s+z*kr[h*4+c],0)/2));
  attention[h]=scores[h].map((r,i)=>softmax(r.map((z,j)=>causal&&j>i?-Infinity:z)));
 }
 const context=x.map((_,i)=>Array.from({length:D},(_,c)=>attention[Math.floor(c/4)][i].reduce((s,a,j)=>s+a*v[j][c],0)));
 const projected=linear(context,w.o,w.ob),r1=add(x,projected),n2=norm(r1),up=linear(n2,w.up,w.ub),activated=up.map(r=>r.map(gelu)),ff=linear(activated,w.down,w.db),r2=add(r1,ff);
 return {input:x,n1,q,k,v,scores,attention,context,projected,r1,n2,up,activated,ff,r2};
}
function forward(ids,causal=true){const embedding=ids.map(id=>tokW[id]),position=ids.map((_,i)=>posW[i]),x=add(embedding,position);const b1=blockForward(x,blocks[0],causal),b2=blockForward(b1.r2,blocks[1],causal),final=norm(b2.r2),logits=matmul(final,outW),probs=logits.map(softmax);return {embedding,position,x,b1,b2,final,logits,probs};}
let state={step:0,token:3,head:0,causal:true,ids:[0,1,2,3],family:0,neuron:0,geluX:1,block:0,generation:'guided'};
let data=forward(state.ids),timer=null;
const $=id=>document.getElementById(id),f=(n,d=3)=>Number(n).toFixed(d),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),nf=n=>n.toLocaleString('pt-BR');
const steps=[
 {nav:'Texto → tokens',title:'Tudo começa com uma sequência.',intro:'Antes de existir uma rede de neurônios, existe uma lista de números. Cada posição será uma linha do tensor.',view:'Tokenização',detail:'Um token não é uma palavra',desc:'O tokenizer associa pedaços de texto a IDs. O ID é um índice: não mede significado ou proximidade entre palavras.',take:'Ordem e identidade são informações diferentes. O token ID representa apenas a identidade.',code:'tokenizer = tiktoken.get_encoding("gpt2")\nids = tokenizer.encode("Hello, I am")\n# [15496, 11, 314, 716]\nin_idx = torch.tensor(ids).unsqueeze(0)'},
 {nav:'Token embedding',title:'Um índice vira um vetor.',intro:'O modelo busca uma linha da tabela de embeddings. A identidade do token passa a ocupar várias dimensões.',view:'Lookup na tabela',detail:'Não é multiplicar pelo ID',desc:'Cada token seleciona uma linha treinável da tabela. As mesmas ocorrências de um ID recebem o mesmo embedding, antes de somar a posição.',take:'As dimensões são características aprendidas em conjunto; não têm significados fixos como “gênero” ou “tempo”.',code:'self.tok_emb = nn.Embedding(vocab_size, emb_dim)\ntok_embeds = self.tok_emb(in_idx)\n# (B, T) → (B, T, D)'},
 {nav:'Posição + dropout',title:'A ordem entra na representação.',intro:'Somamos o vetor do token ao vetor de sua posição, dimensão por dimensão. O tamanho do tensor é preservado.',view:'Soma de embeddings',detail:'Identidade + posição',desc:'O GPT usa embeddings posicionais aprendidos. A posição 0 tem seu próprio vetor, independentemente do token que a ocupa. Depois da soma vem o dropout de embedding.',take:'Aqui usamos inferência: dropout está desligado, como em model.eval(). No treino, ele zera ativações e reescala as restantes.',code:'pos_embeds = self.pos_emb(torch.arange(seq_len))\nx = tok_embeds + pos_embeds\nx = self.drop_emb(x)\n# Em model.eval(), dropout é identidade.'},
 {nav:'LayerNorm 1',title:'Cada token encontra sua escala.',intro:'A normalização acontece dentro de cada vetor. Tokens diferentes não participam da mesma média.',view:'Normalização por token',detail:'Preparar a entrada da atenção',desc:'Calculamos média e variância nas D dimensões do token. Depois normalizamos e aplicamos escala γ e deslocamento β treináveis. Este é um Transformer pre-norm.',take:'A média é aproximadamente 0 e a variância aproximadamente 1 antes da transformação afim. Aqui γ = 1 e β = 0.',code:'shortcut = x\nmean = x.mean(dim=-1, keepdim=True)\nvar = x.var(dim=-1, keepdim=True, unbiased=False)\nx = (x - mean) / torch.sqrt(var + 1e-5)\nx = self.scale * x + self.shift'},
 {nav:'Atenção causal',title:'Os tokens trocam informação.',intro:'Uma query procura keys compatíveis. Os pesos de atenção decidem quanto de cada value entra no novo vetor.',view:'Multi-head attention',detail:'Quem pode olhar para quem?',desc:'Q, K e V são projeções distintas da entrada normalizada. Em cada cabeça, softmax(QKᵀ / √dₕ) produz os pesos usados para combinar V. Concatenamos as cabeças e aplicamos a projeção de saída.',take:'Com máscara causal, um token só consulta a si e ao passado. Desative a máscara para ver o vazamento de informação do futuro.',code:'q, k, v = W_query(x), W_key(x), W_value(x)\n# Dividir D em H cabeças: (B, H, T, D/H)\nscores = q @ k.transpose(-2, -1)\nscores.masked_fill_(mask_bool, -torch.inf)\nweights = torch.softmax(scores / head_dim**0.5, dim=-1)\ncontext = weights @ v\n# Concatenar as cabeças e aplicar out_proj.'},
 {nav:'Residual 1',title:'O caminho original continua vivo.',intro:'A atenção acrescenta uma atualização à representação. Um atalho leva a entrada original até a soma.',view:'Primeira conexão residual',detail:'Somar, sem concatenar',desc:'O atalho desvia da LayerNorm e da atenção. Somamos a saída da atenção ao x que entrou no bloco. No treino, o dropout atua na atualização antes dessa soma.',take:'Os dois caminhos precisam ter o mesmo shape. A conexão residual também facilita a propagação de gradientes no treinamento.',code:'shortcut = x\nx = self.norm1(x)\nx = self.att(x)\nx = self.drop_shortcut(x)\nx = x + shortcut'},
 {nav:'LayerNorm 2 + FFN',title:'Expandir. Transformar. Comprimir.',intro:'Agora cada token é processado individualmente por uma rede densa. As dimensões se conectam; os tokens não se misturam.',view:'Rede feed-forward',detail:'Uma rede dentro do bloco',desc:'Após a segunda LayerNorm, uma projeção expande D para 4D. GELU introduz não linearidade, e outra projeção retorna a D. Os mesmos pesos são aplicados a todas as posições.',take:'A atenção mistura informações entre tokens. O feed-forward transforma as características dentro de cada token.',code:'shortcut = x\nx = self.norm2(x)\nx = self.ff.layers[0](x)  # Linear(D, 4D)\nx = self.ff.layers[1](x)  # GELU\nx = self.ff.layers[2](x)  # Linear(4D, D)'},
 {nav:'Residual 2',title:'Uma segunda atualização se soma.',intro:'O resultado do feed-forward retorna à trilha principal. O primeiro Transformer Block está completo.',view:'Segunda conexão residual',detail:'A mesma largura, mais contexto',desc:'A entrada deste atalho é o resultado da primeira soma residual. O feed-forward opera sobre sua versão normalizada e produz outra atualização de mesma dimensão.',take:'Um bloco inteiro preserva (B, T, D). Isso permite empilhar muitos blocos sem adaptar os shapes entre eles.',code:'shortcut = x\nx = self.norm2(x)\nx = self.ff(x)\nx = self.drop_shortcut(x)\nx = x + shortcut'},
 {nav:'Empilhar blocos',title:'O padrão se repete. Os pesos, não.',intro:'A saída de um bloco alimenta o seguinte. Cada bloco aprende suas próprias projeções e transformações.',view:'Profundidade do GPT',detail:'Dois blocos neste laboratório',desc:'A rede pequena executa dois blocos completos. No GPT-2 Small são 12. A estrutura é repetida, mas cada instância de TransformerBlock tem parâmetros independentes.',take:'Profundidade é uma sequência de transformações. As dimensões de batch, sequência e embedding continuam iguais.',code:'self.trf_blocks = nn.Sequential(\n    *[TransformerBlock(cfg)\n      for _ in range(cfg["n_layers"])]\n)\nx = self.trf_blocks(x)'},
 {nav:'LayerNorm final',title:'Uma última normalização.',intro:'Após todos os blocos, normalizamos cada vetor antes de projetá-lo para o vocabulário.',view:'Normalização final',detail:'Preparar a leitura da saída',desc:'Esta LayerNorm tem seus próprios parâmetros de escala e deslocamento. Ela normaliza a saída do último Transformer Block, novamente ao longo das dimensões de cada token.',take:'Ainda existe um vetor para cada posição. A escolha do último token só acontece depois de calcular os logits.',code:'x = self.trf_blocks(x)\nx = self.final_norm(x)\n# (B, T, D) → (B, T, D)'},
 {nav:'Logits → probabilidades',title:'Um vetor, um placar de candidatos.',intro:'A cabeça de saída projeta D dimensões para V logits. Softmax transforma esse placar em uma distribuição.',view:'Projeção para o vocabulário',detail:'Logit não é probabilidade',desc:'A cabeça é uma camada linear sem bias. Cada posição produz um placar para o próximo token. Exibimos softmax para interpretar a distribuição; o GPTModel retorna logits.',take:'A rede aqui não foi treinada. As probabilidades são cálculos reais do mini-GPT, mas não representam uma previsão linguística confiável.',code:'self.out_head = nn.Linear(D, vocab_size, bias=False)\nlogits = self.out_head(x)\n# (B, T, D) → (B, T, V)\nprobs = torch.softmax(logits, dim=-1)  # visualização'},
 {nav:'Gerar e repetir',title:'A saída se torna a próxima entrada.',intro:'Selecionamos o maior logit da última posição, anexamos o token e executamos todo o modelo novamente.',view:'Geração autoregressiva',detail:'Um token por forward pass',desc:'generate_text_simple usa argmax: escolhe sempre o candidato de maior logit. Não há sorteio. O novo token amplia o contexto da próxima rodada.',take:'Construir a arquitetura não é treinar o modelo. No capítulo 4, pesos aleatórios ainda produzem texto sem coerência.',code:'logits = model(idx_cond)\nlogits = logits[:, -1, :]\nidx_next = torch.argmax(logits, dim=-1, keepdim=True)\nidx = torch.cat((idx, idx_next), dim=1)\n# Repetir com a sequência atualizada.'}
];
const text=(x,y,s,cls='',anchor='start')=>`<text x="${x}" y="${y}" class="${cls}" text-anchor="${anchor}">${esc(s)}</text>`;
const path=(d,active=false)=>`<path d="${d}" class="${active?'flow':'wire'}"/>`;
const rect=(x,y,w,h,label,sub,hot=false)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="7" fill="${hot?'#283b20':'#1b251e'}" stroke="${hot?'#c6f279':'#40513e'}"/>${text(x+w/2,y+h/2+(sub?-3:4),label,hot?'accent':'label','middle')}${sub?text(x+w/2,y+h/2+17,sub,'','middle'):''}`;
const svg=(s,h=350)=>`<svg viewBox="0 0 660 ${h}" role="img" aria-label="${esc(steps[state.step].view)}">${s}</svg>`;
const color=v=>v>=0?`rgba(198,242,121,${.12+Math.min(Math.abs(v)/2,1)*.75})`:`rgba(158,180,175,${.12+Math.min(Math.abs(v)/2,1)*.65})`;
function vector(row,x,y,size=35,labels=true){return row.map((v,i)=>`<g><title>Dimensão ${i}: ${f(v,6)}</title><rect x="${x+i*(size+5)}" y="${y}" width="${size}" height="${size}" rx="4" fill="${color(v)}"/>${labels?text(x+i*(size+5)+size/2,y+size/2+3,f(v,1),'label','middle'):''}</g>`).join('');}
function neuron(x,y,value,hot=false){return `<g><title>Ativação: ${f(value,6)}</title><circle cx="${x}" cy="${y}" r="${hot?9:7}" fill="${hot?'#c6f279':color(value)}" stroke="${hot?'#c6f279':'#6b805e'}"/></g>`;}
function rows(items){$('numbers').innerHTML=items.map(([a,b])=>`<div class="number-row"><span>${a}</span><b>${b}</b></div>`).join('');}
function controls(html){$('stage-controls').innerHTML=html;}
function caption(s){$('caption').innerHTML=s;}
function tokenScene(){
 let s=text(330,33,'“'+state.ids.map(i=>vocab[i]).join('')+'”','label','middle');
 const gap=Math.min(130,560/state.ids.length),start=330-(state.ids.length-1)*gap/2;
 state.ids.forEach((id,i)=>{const x=start+i*gap,hot=i===state.token;s+=path(`M330 53 C330 85 ${x} 70 ${x} 101`,hot)+rect(x-30,104,60,44,vocab[id],'',hot)+path(`M${x} 148 V192`,hot)+rect(x-26,194,52,42,String(id),'',hot)+text(x,268,'pos '+i,'','middle');});
 s+=text(330,320,`IDs locais do mini-GPT · vocabulário com ${V} entradas`,'','middle');
 $('visual').innerHTML=svg(s);rows([['Token selecionado',esc(vocab[state.ids[state.token]])],['ID local',state.ids[state.token]],['Posição',state.token],['Shape',`(1, ${state.ids.length})`]]);caption('Na frase inicial, GPT-2/BPE usaria <b>[15496, 11, 314, 716]</b>. Aqui usamos IDs locais [0, 1, 2, 3] para uma tabela pequena.');
}
function embeddingScene(){let s=text(60,24,`TABELA DE EMBEDDINGS  [${V} × ${D}]`);const id=state.ids[state.token];for(let i=0;i<V;i++){s+=text(23,59+i*33,i, i===id?'accent':'');s+=`<g class="clickable" data-vocab="${i}" role="button" tabindex="0" aria-label="Inspecionar embedding de ${esc(vocab[i])}">`;s+=vector(tokW[i],55,39+i*33,26,false);s+=text(323,58+i*33,vocab[i],i===id?'accent':'');if(i===id)s+=`<rect x="49" y="${35+i*33}" width="264" height="32" rx="4" fill="none" stroke="#c6f279"/>`;s+='</g>';}
 s+=path(`M380 ${52+id*33} C440 ${52+id*33} 403 180 465 180`,true)+rect(463,149,165,60,'ID '+id,'lookup',true);s+=text(330,45+V*33,'Cada quadrado é uma dimensão; passe o mouse para ler o valor.','','middle');$('visual').innerHTML=svg(s,65+V*33);rows([['Tabela do mini-GPT',`${V} × ${D}`],['Parâmetros',V*D],['Vetor selecionado',data.embedding[state.token].slice(0,3).map(v=>f(v,2)).join(' · ')]]);caption('A borda indica a linha usada pelo token selecionado. <b>Os números são pesos fixos não treinados.</b>');}
function sumScene(a,b,out,labels,residual=false){let s='';if(residual){s+=path('M70 62 H590 V261 H480',true)+text(350,51,'atalho: preserva a entrada','','middle');}
 [a,b,out].forEach((r,i)=>{s+=text(70,87+i*87,labels[i],i===2?'accent':'');s+=vector(r,235,65+i*87,39);});s+=text(209,174,'+','accent','middle')+text(209,261,'=','accent','middle');if(residual)s+=text(330,333,'O atalho e a atualização se encontram na soma.','','middle');$('visual').innerHTML=svg(s);const n=state.neuron%D;rows([['Dimensão inspecionada','d'+n],[labels[0],f(a[n])],[labels[1],f(b[n])],['Soma',f(out[n])]]);controls(`<label>Dimensão <select id="dim-select">${a.map((_,i)=>`<option value="${i}" ${i===n?'selected':''}>d${i}</option>`).join('')}</select></label>`);caption('<b>Verde = valor positivo · cinza = negativo.</b> Intensidade representa magnitude. Passe o mouse nos quadrados para ver os números.');}
function normalizationScene(final=false){const before=(final?data.b2.r2:data.x)[state.token],after=(final?data.final:data.b1.n1)[state.token];let s=text(40,25,'ANTES','label')+text(365,25,'DEPOIS · γ=1, β=0','accent');const max=Math.max(2,...before.map(Math.abs),...after.map(Math.abs));[before,after].forEach((r,k)=>{const x=40+k*325;s+=path(`M${x} 170 H${x+255}`);r.forEach((v,i)=>{const h=Math.abs(v)/max*100,y=v>=0?170-h:170;s+=`<rect x="${x+i*32}" y="${y}" width="22" height="${h}" rx="2" fill="${k?'#c6f279':'#75866d'}"><title>d${i}: ${f(v,6)}</title></rect>`+text(x+i*32+11,292,'d'+i,'','middle');});});s+=text(330,335,'(x − média) / √(variância + ε) × γ + β','','middle');$('visual').innerHTML=svg(s);const mean=r=>r.reduce((a,b)=>a+b,0)/r.length,variance=r=>mean(r.map(x=>(x-mean(r))**2));rows([['Média antes → depois',f(mean(before))+' → '+f(mean(after))],['Variância antes → depois',f(variance(before))+' → '+f(variance(after))],['Epsilon','0,00001'],['γ / β','1 / 0']]);caption('Barras acima do eixo são positivas; abaixo, negativas. <b>A estatística usa só as 8 dimensões deste token.</b>');}
function attentionScene(){
 controls(`<button data-head="0" class="${state.head===0?'selected':''}">Cabeça 1</button><button data-head="1" class="${state.head===1?'selected':''}">Cabeça 2</button><button id="mask" class="${state.causal?'selected':''}" aria-pressed="${state.causal}">${state.causal?'● Máscara causal ativa':'○ Sem máscara — comparação'}</button>`);
 const t=state.token,a=data.b1.attention[state.head],dh=4,q=data.b1.q[t].slice(state.head*dh,state.head*dh+dh);let s=text(55,21,'PROJEÇÕES DO TOKEN '+t,'','start');s+=rect(25,50,115,50,'x normalizado','8 dimensões');['Q','K','V'].forEach((l,i)=>{s+=path(`M140 75 C175 75 172 ${35+i*46} 205 ${35+i*46}`,true)+rect(205,17+i*46,94,36,l,'',true);});s+=path('M299 35 H349 V75 H383',true)+path('M299 81 H383',true)+rect(383,51,237,50,'QKᵀ / √4','máscara → softmax',true);s+=text(330,178,'Linhas = queries · colunas = keys · valores = pesos de atenção','','middle');
 let table='<div class="matrix-wrap"><table class="matrix" aria-label="Pesos de atenção"><thead><tr><th>Q ↓ / K →</th>'+state.ids.map((id,j)=>`<th>${j}: ${esc(vocab[id])}</th>`).join('')+'</tr></thead><tbody>';
 table+=a.map((r,i)=>`<tr><th>${i}: ${esc(vocab[state.ids[i]])}</th>${r.map((v,j)=>`<td><button data-cell="${i},${j}" class="${state.causal&&j>i?'masked':''} ${i===t?'current':''}" style="background:rgba(198,242,121,${.08+.9*v});color:${v>.5?'#172111':'#d5e7c7'}" aria-label="Query ${i}, key ${j}, peso ${f(v,4)}">${state.causal&&j>i?'—':f(v,2)}</button></td>`).join('')}</tr>`).join('')+'</tbody></table></div>';
 let bottom='';state.ids.forEach((id,j)=>{const x=50+j*560/(state.ids.length-1);if(a[t][j]>0)bottom+=`<path d="M${x} 33 Q${x} 69 330 98" fill="none" stroke="#c6f279" stroke-opacity="${.18+.82*a[t][j]}" stroke-width="${1+5*a[t][j]}"/>`;bottom+=neuron(x,24,a[t][j],j===t)+text(x,10,'V'+j,'','middle');});bottom+=rect(230,98,200,35,'Σ peso × V','',true)+text(330,155,'concatenar cabeças → projeção Wₒ → 8 dimensões','','middle');
 $('visual').innerHTML=svg(s,185)+table+svg(bottom,165);rows([['Query (4 dimensões)',q.map(v=>f(v,2)).join(', ')],['Soma da linha '+t,f(a[t].reduce((s,v)=>s+v,0),4)],['Cabeças × dimensão','2 × 4 = 8'],['Tokens acessíveis',state.causal?t+1:state.ids.length]]);caption('<b>Clique em uma célula</b> para inspecionar Q·K e o peso. A espessura das conexões abaixo acompanha a linha selecionada.'+(state.causal?'':' <b>Comparação não causal: todas as etapas seguintes também serão recalculadas assim.</b>'));
}
function ffScene(updateOnly=false){
 if(!updateOnly) controls(`<label>Neurônio <select id="neuron-select">${Array.from({length:32},(_,i)=>`<option value="${i}" ${i===state.neuron?'selected':''}>${i}</option>`).join('')}</select></label><label>Explorar GELU: x <input id="gelu-range" type="range" min="-3" max="3" step=".05" value="${state.geluX}"></label><span id="gelu-value">${f(state.geluX,2)} → ${f(gelu(state.geluX),3)}</span>`);
 let s=text(72,24,'8 →','label')+text(270,24,'32 → GELU → 32','accent')+text(562,24,'8','label');const n=state.neuron,t=state.token;for(let i=0;i<8;i++)for(let j=0;j<32;j++){const x=270+(j%2)*55,y=48+Math.floor(j/2)*15;const chosen=j===n;s+=`<path d="M80 ${65+i*30} L${x} ${y}" stroke="${chosen?'#c6f279':'#4b6349'}" stroke-opacity="${chosen?.7:.09}" stroke-width="${chosen?1.2:.65}"/><path d="M${x} ${y} L570 ${65+i*30}" stroke="${chosen?'#c6f279':'#4b6349'}" stroke-opacity="${chosen?.7:.09}" stroke-width="${chosen?1.2:.65}"/>`;}
 for(let i=0;i<8;i++){s+=neuron(80,65+i*30,data.b1.n2[t][i])+neuron(570,65+i*30,data.b1.ff[t][i]);}for(let j=0;j<32;j++)s+=`<g class="clickable" data-neuron="${j}" role="button" tabindex="0" aria-label="Neurônio ${j}">${neuron(270+j%2*55,48+Math.floor(j/2)*15,data.b1.activated[t][j],j===n)}</g>`;
 s+=text(80,319,'entrada normalizada','','middle')+text(300,319,'camada oculta','','middle')+text(570,319,'atualização','','middle');
 const gx=x=>200+(x+3)*44,gy=y=>423-y*25;let curve='';for(let x=-3;x<=3.01;x+=.05)curve+=(curve?'L':'M')+gx(x)+' '+gy(gelu(x))+' ';s+=path('M200 423 H470')+path('M332 346 V441')+`<path d="${curve}" fill="none" stroke="#c6f279" stroke-width="2"/>`+neuron(gx(state.geluX),gy(gelu(state.geluX)),1,true)+text(170,372,'GELU','accent','end')+text(493,419,'x')+text(330,463,'A curva abaixo é um explorador; não altera as ativações da rede.','','middle');
 $('visual').innerHTML=svg(s,480);if(updateOnly)$('gelu-value').textContent=f(state.geluX,2)+' → '+f(gelu(state.geluX),3);rows([['Neurônio oculto',n],['Pré-ativação',f(data.b1.up[t][n])],['Após GELU',f(data.b1.activated[t][n])],['Pesos + biases','552']]);caption('<b>Selecione um dos 32 neurônios</b> para destacar suas 8 conexões de entrada e 8 de saída. GELU atenua valores negativos de forma suave.');
}
function stackScene(){controls(`<button data-block="0" class="${state.block===0?'selected':''}">Inspecionar bloco 1</button><button data-block="1" class="${state.block===1?'selected':''}">Inspecionar bloco 2</button>`);let s='';[0,1].forEach((b)=>{const x=45+b*330;s+=rect(x,42,230,205,'','',state.block===b)+text(x+115,71,'Transformer '+(b+1),state.block===b?'accent':'label','middle');['LayerNorm → atenção','+ residual','LayerNorm → FFN','+ residual'].forEach((l,i)=>s+=text(x+115,111+i*31,l,'','middle'));});s+=path('M275 143 H375',true)+text(325,131,'x','','middle');s+=text(50,290,'Saída do bloco '+(state.block+1),'accent')+vector((state.block===0?data.b1:data.b2).r2[state.token],240,268,39);$('visual').innerHTML=svg(s);const a=(state.block===0?data.b1:data.b2);rows([['Mini-GPT','2 blocos'],['Parâmetros / bloco','848'],['Norma do vetor de entrada',f(Math.hypot(...a.input[state.token]))],['Norma do vetor de saída',f(Math.hypot(...a.r2[state.token]))]]);caption('<b>Clique para comparar as saídas dos blocos.</b> O desenho abrevia os componentes; os dois blocos são calculados por inteiro.');}
function outputScene(generation=false){
 const t=generation?state.ids.length-1:state.token,p=data.probs[t];
 const sorted=p.map((v,i)=>({p:v,id:i,logit:data.logits[t][i]})).sort((a,b)=>b.p-a.p);
 const guided=generation&&state.generation==='guided',chosen=guided?nextGuided(state.ids):sorted[0].id;
 const finished=guided?chosen===null:state.ids.length>=MAX_T;
 if(generation){
  controls(`<label>Modo (reinicia o contexto) <select id="generation-mode"><option value="guided" ${guided?'selected':''}>Frase guiada</option><option value="argmax" ${!guided?'selected':''}>Modelo sem treino · argmax</option></select></label>`);
  if(guided){
   $('title').textContent='Uma frase, construída passo a passo.';
   $('intro').textContent='Acrescente a continuação planejada e observe cada token voltar ao modelo como parte do contexto.';
   $('view-name').textContent='CONTINUAÇÃO GUIADA'+(state.causal?'':' · SEM MÁSCARA');
   $('detail-title').textContent='A frase é escolhida por nós';
   $('explanation').innerHTML='<p>Os próximos tokens seguem o roteiro <strong>“Hello, I am a GPT built from scratch”</strong>. Cada clique acrescenta um ID local e recalcula embeddings, atenção, blocos e logits. As probabilidades abaixo continuam sendo calculadas pela rede sem treino.</p>';
   $('takeaway').textContent='Escolher o token para a demonstração não treina o modelo. Para comparar com a escolha da própria rede, alterne para argmax.';
   $('code').textContent='# Continuação guiada: IDs locais, não BPE\ncontinuation = [4, 8, 9, 10, 11]\nfor token_id in continuation:\n    idx_next = torch.tensor([[token_id]])\n    idx = torch.cat((idx, idx_next), dim=1)\n    logits = model(idx)  # novo forward pass';
  }
 }
 let html=generation?`<div class="big-text">${esc(state.ids.map(id=>vocab[id]).join(''))}<span> ▍</span></div><div class="tagline">${guided?'FRASE GUIADA · '+Math.max(0,state.ids.length-4)+'/5 tokens acrescentados':'ARGMAX · última posição: '+t}</div>`:svg(path('M154 60 H250',true)+rect(20,34,134,52,'vetor final','8 dimensões')+rect(250,34,165,52,'cabeça linear',`W: 8 × ${V}`,true)+path('M415 60 H500',true)+rect(500,34,135,52,'logits',`${V} candidatos`)+text(330,120,'softmax(logits) · posição '+t,'','middle'),135);
 if(generation){
  html+=`<button id="generate" class="primary gen-action" ${finished?'disabled':''}>${finished?(guided?'✓ Frase completa':`Contexto de ${MAX_T} tokens atingido`):'Adicionar “'+esc(vocab[chosen])+'” e recalcular ↻'}</button><p class="small-note">${finished?'Use Reiniciar para começar novamente.':guided?'token do roteiro → anexar → novo forward pass':'argmax → anexar → novo forward pass'}</p>`;
  if(guided)html+='<div class="tagline">PROBABILIDADES DA REDE SEM TREINO · não determinam a frase guiada</div>';
 }
 html+='<div class="prob-list">'+sorted.map(r=>`<div class="prob ${guided&&r.id===chosen?'guided-choice':''}"><span>${esc(vocab[r.id])}${guided&&r.id===chosen?' ←':''}</span><div class="prob-track" title="Logit: ${f(r.logit,6)}"><div class="prob-fill" style="width:${r.p*100}%"></div></div><span>${f(r.p*100,1)}%</span></div>`).join('')+'</div>';
 $('visual').innerHTML=html;
 rows([['Posição lida',t],['Argmax da rede',esc(vocab[sorted[0].id])],[guided?'Próximo no roteiro':'Token escolhido',finished?'—':esc(vocab[chosen])],...(guided&&!finished?[['P(token do roteiro)',f(p[chosen]*100,2)+'%']]:[]),['Σ probabilidades',f(p.reduce((a,b)=>a+b,0),4)]]);
 caption(guided?'<b>Roteiro explícito, cálculo real.</b> A seta marca o próximo token guiado. Os IDs e a divisão em tokens são locais a esta demonstração.':generation?`<b>O botão executa uma rodada de geração por argmax.</b> Contexto didático máximo: ${MAX_T} posições.`:`Os ${V} candidatos representam <b>todo o vocabulário do mini-GPT</b>. No GPT-2, seriam 50.257 logits em cada posição.`);
}
function renderVisual(){$('visual').className=state.step===4?'attention-view':'';controls('');const t=state.token;switch(state.step){case 0:tokenScene();break;case 1:embeddingScene();break;case 2:sumScene(data.embedding[t],data.position[t],data.x[t],['Token embedding','Posição '+t,'Entrada do bloco']);break;case 3:normalizationScene();break;case 4:attentionScene();break;case 5:sumScene(data.x[t],data.b1.projected[t],data.b1.r1[t],['Atalho x','Atenção projetada','Primeira residual'],true);break;case 6:ffScene();break;case 7:sumScene(data.b1.r1[t],data.b1.ff[t],data.b1.r2[t],['Atalho residual 1','Feed-forward','Saída do bloco'],true);break;case 8:stackScene();break;case 9:normalizationScene(true);break;case 10:outputScene();break;case 11:outputScene(true);}}
function shapeInfo(){const T=state.ids.length,c=families[state.family],mini=`(1, ${T}, 8)`,real=`(1, ${T}, ${c.d})`;let si=mini,so=mini,rs=real;if(state.step===0){si='texto';so=`(1, ${T})`;rs=`(1, ${T})`;}if(state.step===1)si=`(1, ${T})`;if(state.step===10){so=`(1, ${T}, ${V} logits)`;rs=`(1, ${T}, 50.257)`;}if(state.step===11){si=`(1, ${T})`;so=state.generation==='guided'&&nextGuided(state.ids)===null?'frase completa':T<MAX_T?`(1, ${T+1})`:`limite didático: ${MAX_T}`;rs=`(1, ${T}) → (1, ${T+1})`;}$('shape-in').textContent=si;$('shape-out').textContent=so;$('real-label').textContent='REFERÊNCIA GPT-2 '+c.name;$('real-shape').textContent=rs;const per=12*c.d*c.d+10*c.d,total=2*50257*c.d+1024*c.d+c.l*per+2*c.d,tied=total-50257*c.d;$('reference').innerHTML=`<b>GPT-2 ${c.name}</b> · D ${nf(c.d)} · ${c.h} cabeças · ${c.l} blocos<br>${nf(total)} parâmetros na implementação do capítulo.<br>${nf(tied)} com weight tying · ${f(total*4/1024**2,0)} MiB de pesos FP32.<br>QKV sem bias · saída independente · contexto 1.024.<br><span>Mini-GPT: ${nf(2*V*D+MAX_T*D+2*848+2*D)} parâmetros, inferência sem dropout.</span>`;}
function render(){const s=steps[state.step];$('steps').innerHTML=steps.map((st,i)=>`<button class="step ${i===state.step?'active':i<state.step?'done':''}" data-step="${i}" ${i===state.step?'aria-current="step"':''}><span class="idx">${String(i+1).padStart(2,'0')}</span><span class="step-label">${st.nav}</span></button>`).join('');$('chapter').textContent=`CAPÍTULO 04 / ${state.step<3?'REPRESENTAR':state.step<9?'TRANSFORMAR':'GERAR'}`;$('title').textContent=s.title;$('intro').textContent=s.intro;$('step-num').textContent=String(state.step+1).padStart(2,'0');$('view-name').textContent=s.view+(state.causal?'':' · SEM MÁSCARA');$('detail-title').textContent=s.detail;$('explanation').innerHTML='<p>'+s.desc+'</p>';$('takeaway').textContent=s.take;$('code').textContent=s.code;$('tokens').innerHTML=state.ids.map((id,i)=>`<button class="token ${i===state.token?'active':''}" data-token="${i}" aria-pressed="${i===state.token}">${esc(vocab[id])}<small>${i}</small></button>`).join('');$('progress').style.width=((state.step+1)/steps.length*100)+'%';$('prev').disabled=state.step===0;$('next').disabled=state.step===11;renderVisual();shapeInfo();updatePlay();}
function updatePlay(){$('play').textContent=timer?'Ⅱ Pausar':'▶ Reproduzir';$('play-status').textContent=timer?'Reprodução automática · '+(state.step+1)+'/12':'Explore no seu ritmo';}
function pause(){if(timer)clearInterval(timer);timer=null;updatePlay();}
function go(step,manual=true){if(manual)pause();state.step=Math.max(0,Math.min(11,step));if(state.step===11)state.token=state.ids.length-1;render();window.scrollTo(0,0);if(window.innerWidth<900)$('steps').querySelector('.active').scrollIntoView({block:'nearest',inline:'center'});}
function play(){if(timer){pause();return;}if(state.step===11)go(0);timer=setInterval(()=>{if(state.step>=11){pause();return;}go(state.step+1,false);if(state.step===11)pause();},Number($('speed').value));updatePlay();}
$('zoom').onclick=()=>{const on=document.body.classList.toggle('diagram-focus');$('zoom').textContent=on?'Voltar à visão completa ↙':'Ampliar diagrama ↗';$('zoom').setAttribute('aria-pressed',on);};
$('prev').onclick=()=>go(state.step-1);$('next').onclick=()=>go(state.step+1);$('play').onclick=play;$('speed').onchange=()=>{if(timer){pause();play();}};$('family').onchange=e=>{state.family=Number(e.target.value);shapeInfo();};$('reset').onclick=()=>{pause();state.ids=[0,1,2,3];state.token=3;state.causal=true;data=forward(state.ids);render();};
$('about').onclick=()=>{pause();$('guide').showModal();};$('close-guide').onclick=$('start').onclick=()=>$('guide').close();$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('fullscreen').textContent='Use a tela cheia do navegador';}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-step],[data-token],[data-head],[data-block],[data-neuron],[data-cell],[data-vocab],#mask,#generate');if(!b)return;
 if(b.dataset.step!==undefined){go(Number(b.dataset.step));return;}if(b.dataset.token!==undefined){state.token=Number(b.dataset.token);if(state.step===11){state.step=10;pause();}render();return;}
 if(b.dataset.head!==undefined)state.head=Number(b.dataset.head);
 if(b.dataset.block!==undefined)state.block=Number(b.dataset.block);
 if(b.dataset.neuron!==undefined)state.neuron=Number(b.dataset.neuron);
 if(b.id==='mask'){state.causal=!state.causal;data=forward(state.ids,state.causal);render();return;}
 if(b.id==='generate'){if(state.ids.length>=MAX_T)return;const p=data.logits.at(-1),id=state.generation==='guided'?nextGuided(state.ids):p.indexOf(Math.max(...p));if(id===null)return;state.ids.push(id);state.token=state.ids.length-1;data=forward(state.ids,state.causal);render();return;}
 if(b.dataset.cell!==undefined){const [i,j]=b.dataset.cell.split(',').map(Number);state.token=i;render();const score=data.b1.scores[state.head][i][j];rows([['Query / key',`${i} → ${j}`],['Q·K / √4',f(score,5)],['Após máscara',state.causal&&j>i?'−∞':f(score,5)],['Peso softmax',f(data.b1.attention[state.head][i][j],5)],['Contribuição','peso × V'+j]]);return;}
 if(b.dataset.vocab!==undefined){const id=Number(b.dataset.vocab);rows([['Linha da tabela',id],['Token',esc(vocab[id])],['d0',f(tokW[id][0],6)],['d1',f(tokW[id][1],6)]]);return;}
 renderVisual();});
document.addEventListener('change',e=>{if(e.target.id==='generation-mode'){pause();state.generation=e.target.value;state.ids=[0,1,2,3];state.token=3;data=forward(state.ids,state.causal);render();return;}if(e.target.id==='dim-select'||e.target.id==='neuron-select'){state.neuron=Number(e.target.value);renderVisual();}});
document.addEventListener('input',e=>{if(e.target.id==='gelu-range'){state.geluX=Number(e.target.value);ffScene(true);}});
document.addEventListener('keydown',e=>{if($('guide').open)return;const tag=e.target.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(e.key==='ArrowRight'){e.preventDefault();go(state.step+1);return;}if(e.key==='ArrowLeft'){e.preventDefault();go(state.step-1);return;}if(e.target.closest('[role="button"]')){if(e.key==='Enter'||e.key===' '){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}return;}if(['BUTTON','SUMMARY','A'].includes(tag))return;if(e.code==='Space'){e.preventDefault();play();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
render();
