window.JOURNEY_DATA = {
  "source": "lesson/chapter4_visual_lesson.ipynb",
  "sha256": "056a05d0662e1f0e4138ab31aea12f294fb5a261fb96f5052d7cd87fb5fc817a",
  "ids": [
    15496,
    11,
    314,
    716
  ],
  "generated": [
    15496,
    11,
    314,
    716,
    27018,
    24086,
    47843,
    30961,
    42348,
    7267,
    49706,
    43231,
    47062,
    34657
  ],
  "text": "Hello, I am Featureiman Byeswickattribute argue logger Normandy Compton analogous",
  "records": {
    "4": {
      "cell": 4,
      "code": "model = GPTModel(GPT_CONFIG_124M)\n\ntotal = sum(p.numel() for p in model.parameters())\ntok = model.tok_emb.weight.numel()\nhead = model.out_head.weight.numel()\n\nprint(f\"Total de parâmetros:        {total:,}\")\nprint(f\"Token embedding (tok_emb):  {tok:,}\")\nprint(f\"Output head (out_head):     {head:,}\")\nprint(f\"Sem a out_head (tie):       {total - head:,}   <- é daqui que vem 'GPT-124M'\")\nprint(f\"Tamanho em float32:         {total*4/1024/1024:.1f} MB\")",
      "output": "Total de parâmetros:        163,009,536\nToken embedding (tok_emb):  38,597,376\nOutput head (out_head):     38,597,376\nSem a out_head (tie):       124,412,160   <- é daqui que vem 'GPT-124M'\nTamanho em float32:         621.8 MB\n"
    },
    "8": {
      "cell": 8,
      "code": "VOCAB, CTX = 50257, 768  # nota: ctx do pos_emb; usamos 1024 no forward mas a tabela é 1024\nCTX = 1024\n\ndef count_params(emb, layers, tie=False):\n    \"\"\"Fórmula fechada para ESTA arquitetura (qkv_bias=False).\"\"\"\n    tok  = VOCAB * emb            # token embedding\n    pos  = CTX * emb              # positional embedding\n    per_block = 12 * emb**2 + 10 * emb   # MHA (4emb²+emb) + FFN (8emb²+5emb) + 2·LayerNorm (4emb)\n    final_norm = 2 * emb\n    head = emb * VOCAB            # out_head\n    total = tok + pos + layers * per_block + final_norm + head\n    return total - (head if tie else 0)   # tie=True simula o weight tying do GPT-2\n\n# valida a fórmula contra o modelo real que instanciamos na seção 1\nassert count_params(768, 12) == total, \"fórmula não bate com o modelo instanciado!\"\nprint(\"fórmula validada contra o GPTModel real ✓\\n\")\n\nFAMILY = {\n    \"Small\":  dict(emb=768,  layers=12, heads=12),\n    \"Medium\": dict(emb=1024, layers=24, heads=16),\n    \"Large\":  dict(emb=1280, layers=36, heads=20),\n    \"XL\":     dict(emb=1600, layers=48, heads=25),\n}\n\nprint(f\"{'modelo':<8}{'emb':>6}{'layers':>8}{'heads':>7}{'params (163M-style)':>22}{'com weight tying':>20}\")\nprint(\"-\"*72)\nfor name, c in FAMILY.items():\n    untied = count_params(c[\"emb\"], c[\"layers\"])\n    tied   = count_params(c[\"emb\"], c[\"layers\"], tie=True)\n    print(f\"{name:<8}{c['emb']:>6}{c['layers']:>8}{c['heads']:>7}{untied/1e6:>19.1f}M{tied/1e6:>18.1f}M\")",
      "output": "fórmula validada contra o GPTModel real ✓\n\nmodelo     emb  layers  heads   params (163M-style)    com weight tying\n------------------------------------------------------------------------\nSmall      768      12     12              163.0M             124.4M\nMedium    1024      24     16              406.2M             354.7M\nLarge     1280      36     20              838.2M             773.9M\nXL        1600      48     25             1637.8M            1557.4M\n"
    },
    "15": {
      "cell": 15,
      "code": "tokenizer = tiktoken.get_encoding(\"gpt2\")\nids = tokenizer.encode(\"Hello, I am\")\nx = torch.tensor(ids).unsqueeze(0)\nprint(\"Texto:  'Hello, I am'\")\nprint(\"Tokens:\", ids, \" -> shape de entrada:\", tuple(x.shape))\n\nlogs = []\ndef hook(module, inp, out):\n    if isinstance(out, torch.Tensor):\n        logs.append((module.__class__.__name__, tuple(out.shape)))\n\nhandles = []\nfor name, m in model.named_modules():\n    # só as peças didáticas do capítulo (evita listar cada Linear interno)\n    if isinstance(m, (nn.Embedding, LayerNorm, FeedForward, TransformerBlock)) or name == \"out_head\":\n        handles.append(m.register_forward_hook(hook))\n\nmodel.eval()\nwith torch.no_grad():\n    _ = model(x)\nfor h in handles: h.remove()\n\nprint(\"\\n{:<22}{}\".format(\"camada\", \"shape de saída\"))\nprint(\"-\"*45)\nfor cls, shp in logs:\n    print(\"{:<22}{}\".format(cls, shp))",
      "output": "Texto:  'Hello, I am'\nTokens: [15496, 11, 314, 716]  -> shape de entrada: (1, 4)\n\ncamada                shape de saída\n---------------------------------------------\nEmbedding             (1, 4, 768)\nEmbedding             (4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLayerNorm             (1, 4, 768)\nFeedForward           (1, 4, 768)\nTransformerBlock      (1, 4, 768)\nLayerNorm             (1, 4, 768)\nLinear                (1, 4, 50257)\n"
    },
    "18": {
      "cell": 18,
      "code": "out = generate_text_simple(model, x, max_new_tokens=10, context_size=GPT_CONFIG_124M[\"context_length\"])\nprint(\"IDs gerados:\", out.squeeze(0).tolist())\nprint(\"Texto:      \", tokenizer.decode(out.squeeze(0).tolist()))",
      "output": "IDs gerados: [15496, 11, 314, 716, 27018, 24086, 47843, 30961, 42348, 7267, 49706, 43231, 47062, 34657]\nTexto:       Hello, I am Featureiman Byeswickattribute argue logger Normandy Compton analogous\n"
    }
  },
  "code": {
    "GPTDatasetV1": "class GPTDatasetV1(Dataset):\n    def __init__(self, txt, tokenizer, max_length, stride):\n        self.input_ids = []\n        self.target_ids = []\n\n        # Tokenize the entire text\n        token_ids = tokenizer.encode(txt, allowed_special={\"<|endoftext|>\"})\n\n        # Use a sliding window to chunk the book into overlapping sequences of max_length\n        for i in range(0, len(token_ids) - max_length, stride):\n            input_chunk = token_ids[i:i + max_length]\n            target_chunk = token_ids[i + 1: i + max_length + 1]\n            self.input_ids.append(torch.tensor(input_chunk))\n            self.target_ids.append(torch.tensor(target_chunk))\n\n    def __len__(self):\n        return len(self.input_ids)\n\n    def __getitem__(self, idx):\n        return self.input_ids[idx], self.target_ids[idx]",
    "create_dataloader_v1": "def create_dataloader_v1(txt, batch_size=4, max_length=256,\n                         stride=128, shuffle=True, drop_last=True, num_workers=0):\n    # Initialize the tokenizer\n    tokenizer = tiktoken.get_encoding(\"gpt2\")\n\n    # Create dataset\n    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)\n\n    # Create dataloader\n    dataloader = DataLoader(\n        dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last, num_workers=num_workers)\n\n    return dataloader",
    "MultiHeadAttention": "class MultiHeadAttention(nn.Module):\n    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):\n        super().__init__()\n        assert d_out % num_heads == 0, \"d_out must be divisible by num_heads\"\n\n        self.d_out = d_out\n        self.num_heads = num_heads\n        self.head_dim = d_out // num_heads  # Reduce the projection dim to match desired output dim\n\n        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)\n        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)\n        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)\n        self.out_proj = nn.Linear(d_out, d_out)  # Linear layer to combine head outputs\n        self.dropout = nn.Dropout(dropout)\n        self.register_buffer(\"mask\", torch.triu(torch.ones(context_length, context_length), diagonal=1))\n\n    def forward(self, x):\n        b, num_tokens, d_in = x.shape\n\n        keys = self.W_key(x)  # Shape: (b, num_tokens, d_out)\n        queries = self.W_query(x)\n        values = self.W_value(x)\n\n        # We implicitly split the matrix by adding a `num_heads` dimension\n        # Unroll last dim: (b, num_tokens, d_out) -> (b, num_tokens, num_heads, head_dim)\n        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)\n        values = values.view(b, num_tokens, self.num_heads, self.head_dim)\n        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)\n\n        # Transpose: (b, num_tokens, num_heads, head_dim) -> (b, num_heads, num_tokens, head_dim)\n        keys = keys.transpose(1, 2)\n        queries = queries.transpose(1, 2)\n        values = values.transpose(1, 2)\n\n        # Compute scaled dot-product attention (aka self-attention) with a causal mask\n        attn_scores = queries @ keys.transpose(2, 3)  # Dot product for each head\n\n        # Original mask truncated to the number of tokens and converted to boolean\n        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]\n\n        # Use the mask to fill attention scores\n        attn_scores.masked_fill_(mask_bool, -torch.inf)\n\n        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)\n        attn_weights = self.dropout(attn_weights)\n\n        # Shape: (b, num_tokens, num_heads, head_dim)\n        context_vec = (attn_weights @ values).transpose(1, 2)\n\n        # Combine heads, where self.d_out = self.num_heads * self.head_dim\n        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)\n        context_vec = self.out_proj(context_vec)  # optional projection\n\n        return context_vec",
    "LayerNorm": "class LayerNorm(nn.Module):\n    def __init__(self, emb_dim):\n        super().__init__()\n        self.eps = 1e-5\n        self.scale = nn.Parameter(torch.ones(emb_dim))\n        self.shift = nn.Parameter(torch.zeros(emb_dim))\n\n    def forward(self, x):\n        mean = x.mean(dim=-1, keepdim=True)\n        var = x.var(dim=-1, keepdim=True, unbiased=False)\n        norm_x = (x - mean) / torch.sqrt(var + self.eps)\n        return self.scale * norm_x + self.shift",
    "GELU": "class GELU(nn.Module):\n    def __init__(self):\n        super().__init__()\n\n    def forward(self, x):\n        return 0.5 * x * (1 + torch.tanh(\n            torch.sqrt(torch.tensor(2.0 / torch.pi)) *\n            (x + 0.044715 * torch.pow(x, 3))\n        ))",
    "FeedForward": "class FeedForward(nn.Module):\n    def __init__(self, cfg):\n        super().__init__()\n        self.layers = nn.Sequential(\n            nn.Linear(cfg[\"emb_dim\"], 4 * cfg[\"emb_dim\"]),\n            GELU(),\n            nn.Linear(4 * cfg[\"emb_dim\"], cfg[\"emb_dim\"]),\n        )\n\n    def forward(self, x):\n        return self.layers(x)",
    "TransformerBlock": "class TransformerBlock(nn.Module):\n    def __init__(self, cfg):\n        super().__init__()\n        self.att = MultiHeadAttention(\n            d_in=cfg[\"emb_dim\"],\n            d_out=cfg[\"emb_dim\"],\n            context_length=cfg[\"context_length\"],\n            num_heads=cfg[\"n_heads\"],\n            dropout=cfg[\"drop_rate\"],\n            qkv_bias=cfg[\"qkv_bias\"])\n        self.ff = FeedForward(cfg)\n        self.norm1 = LayerNorm(cfg[\"emb_dim\"])\n        self.norm2 = LayerNorm(cfg[\"emb_dim\"])\n        self.drop_shortcut = nn.Dropout(cfg[\"drop_rate\"])\n\n    def forward(self, x):\n        # Shortcut connection for attention block\n        shortcut = x\n        x = self.norm1(x)\n        x = self.att(x)   # Shape [batch_size, num_tokens, emb_size]\n        x = self.drop_shortcut(x)\n        x = x + shortcut  # Add the original input back\n\n        # Shortcut connection for feed-forward block\n        shortcut = x\n        x = self.norm2(x)\n        x = self.ff(x)\n        x = self.drop_shortcut(x)\n        x = x + shortcut  # Add the original input back\n\n        return x",
    "GPTModel": "class GPTModel(nn.Module):\n    def __init__(self, cfg):\n        super().__init__()\n        self.tok_emb = nn.Embedding(cfg[\"vocab_size\"], cfg[\"emb_dim\"])\n        self.pos_emb = nn.Embedding(cfg[\"context_length\"], cfg[\"emb_dim\"])\n        self.drop_emb = nn.Dropout(cfg[\"drop_rate\"])\n\n        self.trf_blocks = nn.Sequential(\n            *[TransformerBlock(cfg) for _ in range(cfg[\"n_layers\"])])\n\n        self.final_norm = LayerNorm(cfg[\"emb_dim\"])\n        self.out_head = nn.Linear(cfg[\"emb_dim\"], cfg[\"vocab_size\"], bias=False)\n\n    def forward(self, in_idx):\n        batch_size, seq_len = in_idx.shape\n        tok_embeds = self.tok_emb(in_idx)\n        pos_embeds = self.pos_emb(torch.arange(seq_len, device=in_idx.device))\n        x = tok_embeds + pos_embeds  # Shape [batch_size, num_tokens, emb_size]\n        x = self.drop_emb(x)\n        x = self.trf_blocks(x)\n        x = self.final_norm(x)\n        logits = self.out_head(x)\n        return logits",
    "generate_text_simple": "def generate_text_simple(model, idx, max_new_tokens, context_size):\n    # idx is (B, T) array of indices in the current context\n    for _ in range(max_new_tokens):\n\n        # Crop current context if it exceeds the supported context size\n        # E.g., if LLM supports only 5 tokens, and the context size is 10\n        # then only the last 5 tokens are used as context\n        idx_cond = idx[:, -context_size:]\n\n        # Get the predictions\n        with torch.no_grad():\n            logits = model(idx_cond)\n\n        # Focus only on the last time step\n        # (batch, n_token, vocab_size) becomes (batch, vocab_size)\n        logits = logits[:, -1, :]\n\n        # Get the idx of the vocab entry with the highest logits value\n        idx_next = torch.argmax(logits, dim=-1, keepdim=True)  # (batch, 1)\n\n        # Append sampled index to the running sequence\n        idx = torch.cat((idx, idx_next), dim=1)  # (batch, n_tokens+1)\n\n    return idx",
    "main": "def main():\n    GPT_CONFIG_124M = {\n        \"vocab_size\": 50257,     # Vocabulary size\n        \"context_length\": 1024,  # Context length\n        \"emb_dim\": 768,          # Embedding dimension\n        \"n_heads\": 12,           # Number of attention heads\n        \"n_layers\": 12,          # Number of layers\n        \"drop_rate\": 0.1,        # Dropout rate\n        \"qkv_bias\": False        # Query-Key-Value bias\n    }\n\n    torch.manual_seed(123)\n    model = GPTModel(GPT_CONFIG_124M)\n    model.eval()  # disable dropout\n\n    start_context = \"Hello, I am\"\n\n    tokenizer = tiktoken.get_encoding(\"gpt2\")\n    encoded = tokenizer.encode(start_context)\n    encoded_tensor = torch.tensor(encoded).unsqueeze(0)\n\n    print(f\"\\n{50*'='}\\n{22*' '}IN\\n{50*'='}\")\n    print(\"\\nInput text:\", start_context)\n    print(\"Encoded input text:\", encoded)\n    print(\"encoded_tensor.shape:\", encoded_tensor.shape)\n\n    out = generate_text_simple(\n        model=model,\n        idx=encoded_tensor,\n        max_new_tokens=10,\n        context_size=GPT_CONFIG_124M[\"context_length\"]\n    )\n    decoded_text = tokenizer.decode(out.squeeze(0).tolist())\n\n    print(f\"\\n\\n{50*'='}\\n{22*' '}OUT\\n{50*'='}\")\n    print(\"\\nOutput:\", out)\n    print(\"Output length:\", len(out[0]))\n    print(\"Output text:\", decoded_text)"
  },
  "config": {
    "vocab_size": 50257,
    "context_length": 1024,
    "emb_dim": 768,
    "n_heads": 12,
    "n_layers": 12,
    "drop_rate": 0.1,
    "qkv_bias": false
  }
};
